### ISSUE TITLE
Bake in auto-scaling defaults

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-icd-postgresql#25]
### Description

It may be a good idea to include defaults for auto-scaling in the module itself - based on their current value, so that we can protect consumers from change in default values when not all auto-scaling values are set https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/blob/main/variables.tf#L144

I don't think the default are currently documented anywhere - not found in terraform provider, nor in ICD documentation. they are visible from the UI however.
![image](https://user-images.githubusercontent.com/16447795/218827945-540137c2-bcac-489a-bcf5-0ffbbc820f1e.png)

### New or affected modules

* all icd modules.

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by Soaib024** [comment]
PR merged - hence closing
