### ISSUE TITLE
Prevent setting a CBR rule that include a service as one of the network zone

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-icd-postgresql#26]
### Description

This will end up in an error down the line - so see if we could catch this earlier in tf module execution.

See https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-cbr&interface=ui
"Cloud Databases does not support Reference a service. Selecting a service results in an error when you create a rule."

**Comment by ocofaigh** [comment]
Since there was no straight forward solution here, we are going to close this out and allow the provider to handle the verification. We can revisit if we really need to in the future.
