### ISSUE TITLE
Expose capability to create service credentials in root module - as "first class" citizen

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-icd-postgresql#28]
### Description

Creating service credential is currently exposed in one of the example (at https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/blob/main/examples/complete/main.tf#L125).

However, given that service credential is the primary way to created additional users/password in postgres, it would be desirable to expose this capability directly in the root module via an input variable.

In output, the service credentials json should be exposed. Furthermore, it would be nice to also expose as outputs a few additional variables that exposes some of the key fields from the service credentials to connect (username, password, cert, hostname)

### New or affected modules

* terraform-ibm-icd-postgresql

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by Soaib024** [comment]
@vburckhardt do we really want to expose password?

**Comment by Soaib024** [comment]
PR merged - hence closing
