### ISSUE TITLE
Complete example clean up / additions

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-icd-postgresql#29]
Couple of aspects - https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/tree/main/examples/complete
1. The README at https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/tree/main/examples/complete indicates that the example stores credential in secret manager - but the corresponding code does not ( I suspect this was cur
2. A VPE should be created in the VPC to demonstrate how access can be given to the postgres instance via that VPE

**Comment by jojustin** [comment]
PR Merged and release is made.  Closing this.
