### ISSUE TITLE
Expose host_flavor in module (introduced 1.62.0)

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-icd-postgresql#362]
### Description

New input added to provider / api (from 1.62.0) - https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/database#sample-database-instance-by-using-host_flavor-attribute

Expose it in the module.
Ensure that there is no clash with existing memory, disk, cpu inputs.

**Comment by kierramarie** [comment]
![PR](https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/pull/382) opened.

**Comment by ocofaigh** [comment]
Included in https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/releases/tag/v3.11.0
