### ISSUE TITLE
IBM Cloud Databases for PostgreSQL 11: End of life on February 29, 2024

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-icd-postgresql#367]
https://www.ibm.com/blog/announcement/ibm-cloud-databases-for-postgresql-11-end-of-life-on-february-29-2024/

Remove support for postgres 11 from module

**Comment by ocofaigh** [comment]
PR: https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/pull/372

**Comment by Aashiq-J** [comment]
PR merged. Closing issue
