### ISSUE TITLE
Add support for multitenant host flavor

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-icd-postgresql#404]
### Description

The host_flavor can take a specific id set to "multitenant". When this is the case, cpu, memory, disk can be specified.

The purpose of this ticket is to add the specific handing for multitenant id in the module.

This is a 3rd case to introduce here in parallel to the 2 existing ones.

https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/blob/aeeaae963acf998696dfd064dd927fb2f5472ce8/main.tf#L88

Here is a valid example of usage:
```
data "ibm_resource_group" "group" {
  name = "<your_group>"
}
resource "ibm_database" "<your_database>" {
  name              = "<your_database_name>"
  plan              = "standard"
  location          = "eu-gb"
  service           = "databases-for-etcd"
  resource_group_id = data.ibm_resource_group.group.id
  tags              = ["tag1", "tag2"]
  adminpassword                = "password12"
  group {
    group_id = "member"
    host_flavor {
      id = "multitenant"
    },
    cpu {
      allocation_count = 3
    }
    memory {
      allocation_mb = 2048
    }
    disk {
      allocation_mb = 256000
    }
  }
  users {
    name     = "user123"
    password = "password12"
  }
  allowlist {
    address     = "172.168.1.1/32"
    description = "desc"
  }
}
output "ICD Etcd database connection string" {
  value = "http://${ibm_database.test_acc.ibm_database_connection.icd_conn}"
}
```

**Comment by Ak-sky** [comment]
Available in release https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/releases/tag/v3.12.0, closing this.
