### ISSUE TITLE
Support for creating a new PostgreSQL instance pointing to a PITR time

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-icd-postgresql#44]
### Description

Creating a new PostgreSQL instance pointing to a PITR time. This should be doable leveraging the https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/database#point_in_time_recovery_deployment_id and https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/database#point_in_time_recovery_time fields

### New or affected modules

- [terraform-ibm-icd-postgresql](https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql)

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
Included in https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/releases/tag/v1.5.0
