### ISSUE TITLE
Support for creating read-only replicates

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-icd-postgresql#45]
### Description

This should be doable via https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/database#remote_leader_id

In an initial phase, I think we should simply surface this parameter via the inputs of the module ( + testing)
In a subsequent phase, we could look at baking into the module a flow that can create 1 postgres instance + n read-only replicates.

### New or affected modules

- [terraform-ibm-icd-postgresql](https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql)

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by iamar7** [comment]
PR Merged, closing the issue.
