### ISSUE TITLE
Add prevent_destroy input

### ISSUE THREAD

**Issue by bayedamethiam** [terraform-ibm-modules/terraform-ibm-icd-postgresql#454]
### Description

Add new input prevent_destroy which allow to set the lifecyle block to avoid 
accidental destroy of instance

**Comment by ocofaigh** [comment]
@bayedamethiam We can't add `prevent_destroy = true` in our module for the instance resource because it means terraform destroy will always fail, even if someone wants to actually destroy the instance.
Going to close this issue, but feel free to re-open if you have any further comments

**Comment by bayedamethiam** [comment]
The point is to allow someone to set the parameter. By default it would be false to prevent that issue. If I want to prevent any destruction I can not following this module.

**Comment by ocofaigh** [comment]
@bayedamethiam You can't set the parameter via a variable because terraform needs to know the value of it before it executes. See https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/pull/460#issuecomment-2259026890

**Comment by bayedamethiam** [comment]
@ocofaigh 
I don't get it.
If the default value of the variable is false terraform won't  use it ? 
I mean we cannot create an input parameter for the module to allow us to deactivate the destruction of an instance ?

**Comment by ocofaigh** [comment]
@bayedamethiam Take a look at the limitation in terraform: https://github.com/hashicorp/terraform/issues/22544
It means you cannot do something like this:
```
variable "prevent_destroy" {
  description = "Set to true to prevent accidental destruction of the instance"
  type        = bool
  default     = false
}

lifecycle {
    prevent_destroy = var.prevent_destroy
}
```
