### ISSUE TITLE
Only allow backup key to be set if region is us-south

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-icd-postgresql#49]
### Description

Setting backup key and region to anything other than us-south result in this error at execution / apply time. It would be nice to actually catch this condition at the terraform layer - that'll save consumer time and frustration.

```
│     "Result": {
│         "details": "{\"error\":\"KMSError\",\"description\":\"We were unable to complete your request: Only us-south backup encryption keys are supported. Try again with valid values or contact support if the issue persists.\"}",
│         "error_code": "RC-ServiceBrokerErrorResponse",
│         "message": "Please contact the Service Provider for this error. [400, Bad Request] We were unable to complete your request: Only us-south backup encryption keys are supported. Try again with valid values or contact support if the issue persists.",
│         "status_code": 422,
│         "transaction_id": "bss-563120aebb02e01e"
```

### New or affected modules

- [terraform-ibm-icd-postgresql](https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql)

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
@vburckhardt BYOK for backups is available in `us-south` and `us-east`, and `eu-de`. Only keys in the `us-south` and `eu-de` are durable to region failures thought (see https://cloud.ibm.com/docs/cloud-databases?topic=cloud-databases-key-protect&interface=ui#key-byok).
The tests are set up to use only one of those regions (https://github.com/terraform-ibm-modules/common-dev-assets/blob/main/common-go-assets/icd-region-prefs.yaml).
The module does not actually know what region the key is coming from, so we can't really add any extra logic to catch the error. We have to let the instance api return the error, and ensure the variable descriptions are clear that the Key region matches the instance region, and must be us-south or eu-de.

**Comment by ocofaigh** [comment]
Coming in https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/pull/186
