### ISSUE TITLE
Exclude group block during all restore operations

### ISSUE THREAD

**Issue by shemau** [terraform-ibm-modules/terraform-ibm-icd-postgresql#515]
### Affected modules

* terraform-ibm-icd-*

### Terraform CLI and Terraform provider versions

* Terraform version: All, unrelated
* Provider version: All, unrelated

### Terraform output

```hcl
      + group {
          + group_id = "member"
          + cpu {
              + allocation_count = 0
            }
          + disk {
              + allocation_mb = 5120
            }
          + members {
              + allocation_count = 2
            }
          + memory {
              + allocation_mb = 4096
            }
        }
```

### Expected behavior

The `group` block should be excluded during restore operations to work around a service side issue with validation

### Actual behavior

Following 3.17.10 there are some input values that included backup_crn to request a restore operation that still included the `group` block. The logic for including the deprecated hosting model has an issue that can cause it to be included with the new hosting model requests.

### Steps to reproduce (including links and screen captures)

1. Run `terraform apply`

### Anything else

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
From Steve:

> I think this issue can be closed for now.
> 
> There is one remaining issue open from the consumer with read only replica. The work around, provided by the ICD team for this was modify the request (inputs to the module) rather than to change the module. So at the moment, there is no outstanding work to do.
