### ISSUE TITLE
doc: document known issue in terraform provider around autoscaling block

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-icd-postgresql#52]
### Description

Bug: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4339

Possible workarounds in the meantime:

- Use 1.49 which was reported as working (and https://github.ibm.com/GoldenEye/icd-rabbitmq-module/blob/master/version.tf#L8 say 1.49.0 or higher)
- Make sure that none of the properties are set to null show all the values and types that need to be set (and passed from your deployment to the module.

### New or affected modules

- all icd-* modules that surface the autoscaling block

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by vburckhardt** [comment]
Should this be closed?

**Comment by ocofaigh** [comment]
Yes, we have addressed the issue in a recent release

**Comment by SirSpidey** [comment]
Update at 2023-06-08: Removed the known issue from the docs because we have coded a workaround for the issue.
